import os

# Part 2: Market Intelligence + Quant Model + Investment
with open(r'D:\openclaw-workspace\football_quant_os\reports\spain_cape_verde_report.html', 'a', encoding='utf-8') as f:
    f.write('\n')
    f.write('<div class="page">\n')
    f.write('  <div class="sh"><div class="sn">2</div><div class="st">Market Intelligence (Bloomberg Terminal)</div></div>\n')
    f.write('\n')
    f.write('  <div class="btr"><span class="tk">SPAIN vs CAPE VERDE | 1X2 MARKET</span><span>500.COM FLOW DATA | 2026-06-15 21:05 CST</span></div>\n')
    f.write('  <table class="bt">\n')
    f.write('    <thead><tr><th>Selection</th><th>Odds</th><th>Bet Volume</th><th>Volume %</th><th>Theoretical %</th><th>Hot/Cold</th><th>PnL Impact</th></tr></thead>\n')
    f.write('    <tbody>\n')
    f.write('      <tr><td>Spain</td><td class="up">1.08</td><td>17,109,339</td><td>88.9%</td><td>94.8%</td><td class="dn">-3 (COLD)</td><td class="dn">-429,593</td></tr>\n')
    f.write('      <tr><td>Draw</td><td>12.49</td><td>634,228</td><td>7.8%</td><td>3.5%</td><td class="up">+36 (HOT)</td><td class="up">+6,632,389</td></tr>\n')
    f.write('      <tr><td>Cape Verde</td><td>29.21</td><td>304,926</td><td>3.4%</td><td>1.7%</td><td class="up">+25 (HOT)</td><td class="up">+4,631,749</td></tr>\n')
    f.write('    </tbody>\n')
    f.write('  </table>\n')
    f.write('\n')
    f.write('  <div style="margin-top:24px">\n')
    f.write('    <div class="btr"><span class="tk">HANDICAP &amp; OVER/UNDER MARKETS</span><span>ODDSPORTAL + 500.COM AGGREGATE</span></div>\n')
    f.write('    <table class="bt">\n')
    f.write('      <thead><tr><th>Market</th><th>Line</th><th>Selection</th><th>Odds</th><th>Implied Prob</th><th>Model Prob</th><th>Edge</th><th>Rating</th></tr></thead>\n')
    f.write('      <tbody>\n')
    f.write('        <tr><td>1X2</td><td>-</td><td>Spain</td><td class="dn">1.08</td><td>92.6%</td><td>95.0%</td><td class="dn">-2.4%</td><td class="nt">AVOID</td></tr>\n')
    f.write('        <tr><td>Handicap</td><td>Spain -2</td><td>Spain Win</td><td class="up">1.48</td><td>67.6%</td><td>75.0%</td><td class="up">+7.4%</td><td class="up">BUY</td></tr>\n')
    f.write('        <tr><td>Handicap</td><td>Spain -3</td><td>Spain Win</td><td>1.85</td><td>54.1%</td><td>60.0%</td><td class="up">+5.9%</td><td class="up">BUY</td></tr>\n')
    f.write('        <tr><td>O/U</td><td>3.5</td><td>Over</td><td class="up">1.86</td><td>53.8%</td><td>65.0%</td><td class="up">+11.2%</td><td class="up">STRONG BUY</td></tr>\n')
    f.write('        <tr><td>O/U</td><td>3.5</td><td>Under</td><td>1.96</td><td>51.0%</td><td>35.0%</td><td class="dn">-16.0%</td><td class="dn">SELL</td></tr>\n')
    f.write('      </tbody>\n')
    f.write('    </table>\n')
    f.write('  </div>\n')
    f.write('\n')
    f.write('  <div class="card" style="margin-top:24px">\n')
    f.write('    <div class="ch"><div class="ct">Market Intelligence Summary</div><div class="cbd bdgd">GOLDMAN ANALYSIS</div></div>\n')
    f.write('    <p style="font-size:14px;color:#5f6368;line-height:1.7">\n')
    f.write('      <strong>Bookmaker PnL Structure:</strong> The bookmaker is running a loss-leader strategy on Spain 1X2 (-429K, 2.4% of total handle) while harvesting massive profits on Draw (+6.6M, 36.7%) and Cape Verde (+4.6M, 25.7%). This is classic risk management: the 1.08 price is a marketing tool to attract volume, while the real edge is captured in exotic markets. <strong>Professional capital should avoid 1X2 and focus on handicap and totals where pricing is less distorted by retail flow.</strong>\n')
    f.write('    </p>\n')
    f.write('  </div>\n')
    f.write('</div>\n')
    f.write('\n')
    f.write('<div class="page">\n')
    f.write('  <div class="sh"><div class="sn">3</div><div class="st">Quantitative Model Analysis</div></div>\n')
    f.write('\n')
    f.write('  <div class="card">\n')
    f.write('    <div class="ch"><div class="ct">Model Architecture</div><div class="cbd bdb">XGBOOST v4.0</div></div>\n')
    f.write('    <div class="tc">\n')
    f.write('      <div><div class="bn">8</div><div class="bnl">Ensemble Models</div><p style="font-size:13px;color:#5f6368;margin-top:8px">Heuristic + Poisson + 5 XGBoost variants (2026 CRI, 2022 Specialized, 3-World-Cup, Full History, Club Optimized)</p></div>\n')
    f.write('      <div><div class="bn">34</div><div class="bnl">Input Features</div><p style="font-size:13px;color:#5f6368;margin-top:8px">Historical stats + FIFA Rank + Position Scores (GK/DF/MF/OF) + Coach CRI + xG + Match Context</p></div>\n')
    f.write('    </div>\n')
    f.write('  </div>\n')
    f.write('\n')
    f.write('  <div class="card">\n')
    f.write('    <div class="ch"><div class="ct">Feature Importance (Top 10)</div><div class="cbd bdg">XGBOOST v4.0</div></div>\n')
    f.write('    <ul class="fl">\n')
    f.write('      <li><span class="fr">1</span><span class="fn">xG Total</span><div class="fbtk"><div class="fbf" style="width:66%"></div></div><span class="fv">6.6%</span></li>\n')
    f.write('      <li><span class="fr">2</span><span class="fn">xG Difference</span><div class="fbtk"><div class="fbf" style="width:64%"></div></div><span class="fv">6.4%</span></li>\n')
    f.write('      <li><span class="fr">3</span><span class="fn">Away FIFA Rank</span><div class="fbtk"><div class="fbf" style="width:50%"></div></div><span class="fv">5.0%</span></li>\n')
    f.write('      <li><span class="fr">4</span><span class="fn">Home Avg Goals</span><div class="fbtk"><div class="fbf" style="width:47%"></div></div><span class="fv">4.7%</span></li>\n')
    f.write('      <li><span class="fr">5</span><span class="fn">GK Difference</span><div class="fbtk"><div class="fbf" style="width:45%"></div></div><span class="fv">4.5%</span></li>\n')
    f.write('      <li><span class="fr">6</span><span class="fn">Home FIFA Rank</span><div class="fbtk"><div class="fbf" style="width:43%"></div></div><span class="fv">4.3%</span></li>\n')
    f.write('      <li><span class="fr">7</span><span class="fn">FIFA Points Ratio</span><div class="fbtk"><div class="fbf" style="width:42%"></div></div><span class="fv">4.2%</span></li>\n')
    f.write('      <li><span class="fr">8</span><span class="fn">Home Win Rate</span><div class="fbtk"><div class="fbf" style="width:41%"></div></div><span class="fv">4.1%</span></li>\n')
    f.write('      <li><span class="fr">9</span><span class="fn">Defense Difference</span><div class="fbtk"><div class="fbf" style="width:40%"></div></div><span class="fv">4.0%</span></li>\n')
    f.write('      <li><span class="fr">10</span><span class="fn">Strength Difference</span><div class="fbtk"><div class="fbf" style="width:38%"></div></div><span class="fv">3.8%</span></li>\n')
    f.write('    </ul>\n')
    f.write('  </div>\n')
    f.write('\n')
    f.write('  <div class="card">\n')
    f.write('    <div class="ch"><div class="ct">Model Validation</div><div class="cbd bdb">CROSS-VALIDATION</div></div>\n')
    f.write('    <div class="tc">\n')
    f.write('      <div><div class="bn up">70.3%</div><div class="bnl">OU Accuracy (2022 LOOCV)</div></div>\n')
    f.write('      <div><div class="bn up">53.1%</div><div class="bnl">1X2 Accuracy (2022 LOOCV)</div></div>\n')
    f.write('    </div>\n')
    f.write('  </div>\n')
    f.write('</div>\n')

print('Part 3 written: Market + Quant')
