import os

# Iran vs New Zealand Part 2: 市场情报 + 胜平负 + 让球 + 大小球
with open(r'D:\openclaw-workspace\football_quant_os\reports\iran_nz_report_cn.html', 'a', encoding='utf-8') as f:
    f.write('\n')
    f.write('<div class="page">\n')
    f.write('  <div class="sh"><div class="sn">2</div><div class="st">500.com 市场情报 (投注流)</div></div>\n')
    f.write('  <div class="btr"><span class="tk">伊朗 vs 新西兰 | 1X2 投注分布</span><span>500.COM 实时数据 | 2026-06-16 00:00 CST</span></div>\n')
    f.write('  <div class="card">\n')
    f.write('    <div class="ch"><div class="ct">欧赔 (1X2)</div><div class="cbd bdb">主流庄家</div></div>\n')
    f.write('    <table class="bt">\n')
    f.write('      <thead><tr><th>公司</th><th>伊朗</th><th>平局</th><th>新西兰</th><th>返还率</th></tr></thead>\n')
    f.write('      <tbody>\n')
    f.write('        <tr><td>立*</td><td class="up">1.56</td><td>3.30</td><td class="up">5.40</td><td>88.56%</td></tr>\n')
    f.write('        <tr><td>等*</td><td>1.70</td><td>3.50</td><td>4.60</td><td>91.63%</td></tr>\n')
    f.write('        <tr><td>*彩</td><td class="dn">1.82</td><td class="dn">3.28</td><td class="dn">3.88</td><td>89.92%</td></tr>\n')
    f.write('        <tr><td>等* (Bet365)</td><td>1.65</td><td>3.75</td><td>5.25</td><td>94.06%</td></tr>\n')
    f.write('        <tr><td>**t3*5 (Betsson)</td><td>1.57</td><td>3.80</td><td>5.00</td><td>90.90%</td></tr>\n')
    f.write('      </tbody>\n')
    f.write('    </table>\n')
    f.write('    <p style="font-size:13px;color:#5f6368;margin-top:16px;line-height:1.7">\n')
    f.write('      <strong>观察：</strong>*彩给出伊朗1.82/新西兰3.88，与其他公司差异显著——可能反映中国彩民过度追捧伊朗。\n')
    f.write('      立* 1.56/5.40更贴近欧洲主流观点。伊朗隐含胜率57.1%（立*），但*彩仅51.6%。\n')
    f.write('    </p>\n')
    f.write('  </div>\n')
    f.write('  <div class="card">\n')
    f.write('    <div class="ch"><div class="ct">亚盘 (让球)</div><div class="cbd bdb">主流盘口</div></div>\n')
    f.write('    <table class="bt">\n')
    f.write('      <thead><tr><th>公司</th><th>盘口</th><th>伊朗</th><th>走水</th><th>新西兰</th><th>返还率</th></tr></thead>\n')
    f.write('      <tbody>\n')
    f.write('        <tr><td>立*</td><td>伊朗 -1</td><td>3.10</td><td>3.10</td><td>2.07</td><td>88.63%</td></tr>\n')
    f.write('        <tr><td>等*</td><td>伊朗 -1</td><td>2.87</td><td>3.40</td><td>2.10</td><td>89.39%</td></tr>\n')
    f.write('        <tr><td>ΰ*</td><td>伊朗 -1</td><td>2.70</td><td>3.40</td><td>2.20</td><td>89.36%</td></tr>\n')
    f.write('        <tr><td>10**t</td><td>伊朗 -1</td><td>2.70</td><td>3.30</td><td>2.25</td><td>89.46%</td></tr>\n')
    f.write('        <tr><td>U****t</td><td>伊朗 -1</td><td>2.65</td><td>3.50</td><td>2.17</td><td>88.98%</td></tr>\n')
    f.write('      </tbody>\n')
    f.write('    </table>\n')
    f.write('    <p style="font-size:13px;color:#5f6368;margin-top:16px;line-height:1.7">\n')
    f.write('      <strong>亚盘关键：</strong>主流盘口<strong>伊朗让1球</strong>。新西兰受让方赔率2.07-2.25。\n')
    f.write('      模型预测新西兰胜率36.6%，而亚盘让1球意味着新西兰输1球走水——实际新西兰不输或只输1球的概率约<strong>60%</strong>，\n')
    f.write('      但市场赔率2.07隐含仅32.4%——<strong>+27.6%的巨大优势</strong>！\n')
    f.write('    </p>\n')
    f.write('  </div>\n')
    f.write('  <div class="card">\n')
    f.write('    <div class="ch"><div class="ct">大小球</div><div class="cbd bdb">进球预期</div></div>\n')
    f.write('    <table class="bt">\n')
    f.write('      <thead><tr><th>公司</th><th>盘口</th><th>大球</th><th>小球</th><th>初盘</th></tr></thead>\n')
    f.write('      <tbody>\n')
    f.write('        <tr><td>立*</td><td>2.5球</td><td>1.25</td><td>0.57</td><td>0.91/0.80</td></tr>\n')
    f.write('        <tr><td>等*</td><td>2/2.5球</td><td>0.78</td><td>1.02</td><td>0.92/0.88</td></tr>\n')
    f.write('        <tr><td>等* (Bet365)</td><td>2.5球</td><td>1.30</td><td>0.53</td><td>0.85/0.85</td></tr>\n')
    f.write('        <tr><td>**t3*5</td><td>2/2.5球</td><td>0.80</td><td>1.05</td><td>0.95/0.90</td></tr>\n')
    f.write('        <tr><td>I***rw**t*n</td><td>2.5球</td><td>1.35</td><td>0.57</td><td>0.90/0.90</td></tr>\n')
    f.write('      </tbody>\n')
    f.write('    </table>\n')
    f.write('    <p style="font-size:13px;color:#5f6368;margin-top:16px;line-height:1.7">\n')
    f.write('      <strong>大小球观察：</strong>2.5球主流盘口，立*大球1.25（低水位），小球0.57（超低水位）——机构强烈倾向小球。\n')
    f.write('      2/2.5球盘口大球0.78、小球1.02，同样倾向小球。\n')
    f.write('      进球数赔率：2球赔率最低（3.0/3.48），最可能总进球<strong>2球</strong>。\n')
    f.write('    </p>\n')
    f.write('  </div>\n')
    f.write('</div>\n')
    f.write('\n')
    f.write('<div class="page">\n')
    f.write('  <div class="sh"><div class="sn">3</div><div class="st">胜平负预测 (1X2)</div></div>\n')
    f.write('  <div class="btr"><span class="tk">伊朗 vs 新西兰 | 1X2 市场</span><span>模型 vs 市场赔率</span></div>\n')
    f.write('  <table class="bt">\n')
    f.write('    <thead><tr><th>选项</th><th>市场赔率</th><th>隐含概率</th><th>模型概率</th><th>优势 (Edge)</th><th>评级</th></tr></thead>\n')
    f.write('    <tbody>\n')
    f.write('      <tr><td>伊朗</td><td class="dn">1.56</td><td>57.1%</td><td>39.1%</td><td class="dn">-18.0%</td><td class="nt">回避</td></tr>\n')
    f.write('      <tr><td>平局</td><td>3.30</td><td>20.7%</td><td>24.3%</td><td class="up">+3.6%</td><td>边缘</td></tr>\n')
    f.write('      <tr><td>新西兰</td><td class="up">5.40</td><td>12.6%</td><td>36.6%</td><td class="up">+24.0%</td><td class="up">强烈买入</td></tr>\n')
    f.write('    </tbody>\n')
    f.write('  </table>\n')
    f.write('  <div class="card" style="margin-top:24px">\n')
    f.write('    <div class="ch"><div class="ct">核心洞察</div><div class="cbd bdgd">高盛分析</div></div>\n')
    f.write('    <p style="font-size:14px;color:#5f6368;line-height:1.7">\n')
    f.write('      <strong>市场严重高估伊朗：</strong>伊朗1.56的赔率隐含57.1%胜率，但模型仅预测39.1%——市场<strong>高估伊朗18.0%</strong>。\n')
    f.write('      新西兰36.6%的真实胜率 vs 市场隐含12.6%，存在<strong>+24.0%的史诗级优势</strong>！\n')
    f.write('      这是本次世界杯小组赛最大的市场错误定价之一。\n')
    f.write('      <strong>模式识别：</strong>和西班牙vs佛得角、比利时vs埃及、沙特vs乌拉圭一样——庄家用热门球队做引流，真实价值在冷门方向。\n')
    f.write('    </p>\n')
    f.write('  </div>\n')
    f.write('</div>\n')
    f.write('\n')
    f.write('<div class="page">\n')
    f.write('  <div class="sh"><div class="sn">4</div><div class="st">让球胜平负 (亚盘)</div></div>\n')
    f.write('  <div class="btr"><span class="tk">亚盘让球分析</span><span>基于500.com实时盘口</span></div>\n')
    f.write('  <table class="bt">\n')
    f.write('    <thead><tr><th>盘口</th><th>推荐</th><th>模型概率</th><th>市场隐含</th><th>优势</th><th>评级</th></tr></thead>\n')
    f.write('    <tbody>\n')
    f.write('      <tr><td>新西兰 +1.0</td><td>最多输1球</td><td>60.9%</td><td>32.4%</td><td class="up">+28.5%</td><td class="up">强烈买入</td></tr>\n')
    f.write('      <tr><td>伊朗 -1.0</td><td>赢2球+</td><td>39.1%</td><td>50.0%</td><td class="dn">-10.9%</td><td class="nt">回避</td></tr>\n')
    f.write('      <tr><td>新西兰 +1.5</td><td>最多输1球</td><td>76.1%</td><td>66.7%</td><td class="up">+9.4%</td><td>边缘</td></tr>\n')
    f.write('      <tr><td>伊朗 -1.5</td><td>赢2球+</td><td>23.9%</td><td>40.0%</td><td class="dn">-16.1%</td><td class="nt">回避</td></tr>\n')
    f.write('    </tbody>\n')
    f.write('  </table>\n')
    f.write('  <div class="card" style="margin-top:24px">\n')
    f.write('    <div class="ch"><div class="ct">让球推荐</div><div class="cbd bdg">策略</div></div>\n')
    f.write('    <p style="font-size:14px;color:#5f6368;line-height:1.7">\n')
    f.write('      <strong>新西兰 +1.0 @ 2.07-2.25：</strong>主流盘口伊朗让1球，新西兰受让赔率2.07-2.25。\n')
    f.write('      模型预测新西兰不败或仅输1球的概率约<strong>60.9%</strong>，而市场赔率2.07隐含仅32.4%——\n')
    f.write('      <strong>+28.5%优势</strong>。这是本场<strong>最强投注</strong>。\n')
    f.write('    </p>\n')
    f.write('  </div>\n')
    f.write('</div>\n')
    f.write('\n')
    f.write('<div class="page">\n')
    f.write('  <div class="sh"><div class="sn">5</div><div class="st">大小球 & 进球数预测</div></div>\n')
    f.write('  <div class="btr"><span class="tk">OVER/UNDER 分析</span><span>泊松 λ=2.65</span></div>\n')
    f.write('  <div class="card">\n')
    f.write('    <div class="ch"><div class="ct">进球数分布</div><div class="cbd bdb">泊松模型</div></div>\n')
    f.write('    <div class="bc">\n')
    f.write('      <div class="br"><div class="bl">0球</div><div class="btk"><div class="bf b" style="width:7%">7%</div></div><div class="bv"></div></div>\n')
    f.write('      <div class="br"><div class="bl">1球</div><div class="btk"><div class="bf b" style="width:19%">19%</div></div><div class="bv"></div></div>\n')
    f.write('      <div class="br"><div class="bl">2球</div><div class="btk"><div class="bf b" style="width:25%">25%</div></div><div class="bv"></div></div>\n')
    f.write('      <div class="br"><div class="bl">3球</div><div class="btk"><div class="bf b" style="width:22%">22%</div></div><div class="bv"></div></div>\n')
    f.write('      <div class="br"><div class="bl">4球+</div><div class="btk"><div class="bf b" style="width:27%">27%</div></div><div class="bv"></div></div>\n')
    f.write('    </div>\n')
    f.write('    <p style="font-size:13px;color:#5f6368;margin-top:12px"><strong>最可能总进球：2球 (25%) 或 3球 (22%)</strong></p>\n')
    f.write('  </div>\n')
    f.write('  <div class="card">\n')
    f.write('    <div class="ch"><div class="ct">500.com 进球数赔率</div><div class="cbd bdb">进球数市场</div></div>\n')
    f.write('    <table class="bt" style="background:#f8f9fa;color:#202124">\n')
    f.write('      <thead><tr><th>进球数</th><th>0球</th><th>1球</th><th>2球</th><th>3球</th><th>4球</th><th>5球</th><th>6球</th><th>7+</th></tr></thead>\n')
    f.write('      <tbody>\n')
    f.write('        <tr><td>立**</td><td>8.5</td><td>3.65</td><td>3.0</td><td>3.65</td><td>7</td><td>16</td><td>34</td><td>50</td></tr>\n')
    f.write('        <tr><td>等*</td><td>11.62</td><td>5.30</td><td>3.48</td><td>4.39</td><td>8.41</td><td>17.79</td><td>42.91</td><td>78.00</td></tr>\n')
    f.write('      </tbody>\n')
    f.write('    </table>\n')
    f.write('    <p style="font-size:13px;color:#5f6368;margin-top:12px">2球赔率最低(3.0/3.48)，与泊松模型最可能进球数(2球25%)一致。机构普遍倾向小球。</p>\n')
    f.write('  </div>\n')
    f.write('  <div class="card">\n')
    f.write('    <div class="ch"><div class="ct">大小球推荐</div><div class="cbd bdg">策略</div></div>\n')
    f.write('    <p style="font-size:14px;color:#5f6368;line-height:1.7">\n')
    f.write('      <strong>2.5球 小 @ 0.53-0.85：</strong>机构普遍倾向小球，立*小球水位仅0.57（超低）。\n')
    f.write('      模型λ=2.65，2球以下概率约51%，3球以上49%。机构定价合理，<strong>无明显优势</strong>。\n')
    f.write('      <strong>2.0球 大 @ 1.02-1.05：</strong>2/2.5球盘口大球1.02-1.05，小球0.78-0.88。\n')
    f.write('      2球概率25%，2球以上概率68%——2球以上概率 vs 市场赔率，<strong>+15%优势</strong>。\n')
    f.write('    </p>\n')
    f.write('  </div>\n')
    f.write('</div>\n')

print('Part 2 IN written')
