import os

# Iran vs New Zealand 中文报告 Part 1
with open(r'D:\openclaw-workspace\football_quant_os\reports\iran_nz_report_cn.html', 'w', encoding='utf-8') as f:
    f.write('<!DOCTYPE html>\n<html lang="zh-CN">\n<head><meta charset="UTF-8"><title>伊朗 vs 新西兰 - 2026世界杯</title>\n')
    f.write('<style>\n')
    f.write('@import url("https://fonts.googleapis.com/css2?family=Noto+Sans+SC:wght@300;400;500;600;700;900&family=Roboto+Mono:wght@400;500;600&display=swap");\n')
    f.write(':root{--gb:#1a73e8;--gg:#34a853;--gr:#ea4335;--gy:#fbbc04;--ggr:#5f6368;--bbg:#0a0a0a;--bg:#00ff00;--br:#ff3333;--bt:#e6e6e6;--gsb:#003087;--gsl:#e8f0fe;--gsg:#c9a227;--gsn:#001a4d}\n')
    f.write('body{font-family:"Noto Sans SC",sans-serif;color:#202124;background:#fff;line-height:1.6}\n')
    f.write('.cover{height:100vh;background:linear-gradient(135deg,#001a4d 0%,#003087 50%,#005eb8 100%);display:flex;flex-direction:column;justify-content:center;align-items:center;text-align:center;color:white;position:relative}\n')
    f.write('.cover h1{font-size:64px;font-weight:900;letter-spacing:-2px;margin-bottom:16px;text-shadow:0 2px 40px rgba(0,0,0,0.3)}\n')
    f.write('.cs{font-size:20px;font-weight:300;opacity:0.9;margin-bottom:48px;letter-spacing:1px}\n')
    f.write('.cm{display:flex;gap:48px;font-size:14px;opacity:0.7}\n')
    f.write('.cmi{text-align:center}\n')
    f.write('.cmi .l{font-size:11px;text-transform:uppercase;letter-spacing:2px;margin-bottom:4px}\n')
    f.write('.cmi .v{font-size:18px;font-weight:600;font-family:"Roboto Mono",monospace}\n')
    f.write('.cf{position:absolute;bottom:40px;font-size:12px;opacity:0.5;letter-spacing:1px}\n')
    f.write('.page{padding:48px 64px;max-width:900px;margin:0 auto;min-height:100vh}\n')
    f.write('.sh{display:flex;align-items:center;margin-bottom:32px;padding-bottom:16px;border-bottom:3px solid var(--gsb)}\n')
    f.write('.sn{background:var(--gsb);color:white;width:40px;height:40px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-weight:700;font-size:18px;margin-right:16px;font-family:"Roboto Mono",monospace}\n')
    f.write('.st{font-size:28px;font-weight:700;color:var(--gsn);letter-spacing:-0.5px}\n')
    f.write('.card{background:white;border-radius:12px;box-shadow:0 1px 3px rgba(0,0,0,0.08),0 4px 12px rgba(0,0,0,0.05);padding:24px;margin-bottom:24px;border:1px solid #e8eaed}\n')
    f.write('.ch{display:flex;justify-content:space-between;align-items:center;margin-bottom:16px}\n')
    f.write('.ct{font-size:16px;font-weight:600;color:#3c4043;display:flex;align-items:center;gap:8px}\n')
    f.write('.cbd{font-size:11px;padding:4px 10px;border-radius:12px;font-weight:600;text-transform:uppercase;letter-spacing:0.5px}\n')
    f.write('.bdg{background:#e6f4ea;color:var(--gg)}\n')
    f.write('.bdr{background:#fce8e8;color:var(--gr)}\n')
    f.write('.bdb{background:var(--gsl);color:var(--gsb)}\n')
    f.write('.bdgd{background:rgba(201,162,39,0.15);color:var(--gsg)}\n')
    f.write('.bdw{background:#fce8e8;color:var(--gr)}\n')
    f.write('.es{background:linear-gradient(180deg,#f8f9fa 0%,#fff 100%);border-left:4px solid var(--gsb);padding:24px 32px;margin-bottom:32px;border-radius:0 8px 8px 0}\n')
    f.write('.es h3{font-size:13px;text-transform:uppercase;letter-spacing:2px;color:var(--gsb);margin-bottom:16px;font-weight:700}\n')
    f.write('.mc{font-size:22px;font-weight:700;color:var(--gsn);margin-bottom:16px;line-height:1.3}\n')
    f.write('.sp{list-style:none;padding:0}\n')
    f.write('.sp li{padding:8px 0;padding-left:24px;position:relative;font-size:15px;color:#5f6368;border-bottom:1px solid #e8eaed}\n')
    f.write('.sp li:last-child{border-bottom:none}\n')
    f.write('.sp li::before{content:">";position:absolute;left:0;color:var(--gsb);font-weight:700}\n')
    f.write('.bt{width:100%;border-collapse:collapse;font-family:"Roboto Mono",monospace;font-size:13px;background:var(--bbg);color:var(--bt);border-radius:8px;overflow:hidden}\n')
    f.write('.bt th{background:#1a1a1a;padding:12px 16px;text-align:left;font-weight:600;color:#888;text-transform:uppercase;font-size:11px;letter-spacing:1px;border-bottom:2px solid #333}\n')
    f.write('.bt td{padding:12px 16px;border-bottom:1px solid #1a1a1a}\n')
    f.write('.btr{font-family:"Roboto Mono",monospace;font-size:14px;font-weight:600;display:flex;justify-content:space-between;align-items:center;padding:16px 20px;border-radius:8px 8px 0 0;background:var(--bbg);color:var(--bt)}\n')
    f.write('.btr .tk{color:var(--bg);font-weight:700}\n')
    f.write('.up{color:var(--bg)}\n')
    f.write('.dn{color:var(--br)}\n')
    f.write('.nt{color:#888}\n')
    f.write('.mg{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-bottom:24px}\n')
    f.write('.mcd{background:white;border-radius:12px;padding:20px;box-shadow:0 1px 3px rgba(0,0,0,0.08);border:1px solid #e8eaed;text-align:center}\n')
    f.write('.mv{font-size:36px;font-weight:700;font-family:"Roboto Mono",monospace;color:var(--gsn);margin-bottom:4px}\n')
    f.write('.mv.up{color:var(--gg)}\n')
    f.write('.mv.dn{color:var(--gr)}\n')
    f.write('.mv.warn{color:#ff9800}\n')
    f.write('.ml{font-size:12px;color:var(--ggr);text-transform:uppercase;letter-spacing:1px;font-weight:600}\n')
    f.write('.ms{font-size:13px;color:#9aa0a6;margin-top:4px}\n')
    f.write('.ib{background:linear-gradient(135deg,var(--gsl) 0%,#fff 100%);border:2px solid var(--gsb);border-radius:12px;padding:32px;margin-bottom:24px;position:relative}\n')
    f.write('.ib::before{content:"";position:absolute;top:0;left:0;right:0;height:4px;background:var(--gsg);border-radius:12px 12px 0 0}\n')
    f.write('.it{font-size:18px;font-weight:700;color:var(--gsn);margin-bottom:20px}\n')
    f.write('.ig{display:grid;grid-template-columns:repeat(2,1fr);gap:20px}\n')
    f.write('.ii{background:white;border-radius:8px;padding:16px;border:1px solid #e8eaed}\n')
    f.write('.ii .p{font-size:14px;font-weight:600;color:var(--gsn);margin-bottom:8px}\n')
    f.write('.ii .d{font-family:"Roboto Mono",monospace;font-size:13px;color:#5f6368;line-height:1.6}\n')
    f.write('.ii .sk{font-size:24px;font-weight:700;color:var(--gsb);font-family:"Roboto Mono",monospace;margin-top:8px}\n')
    f.write('.ii .ev{font-size:14px;font-weight:600;color:var(--gg)}\n')
    f.write('.ii .warn{font-size:14px;font-weight:600;color:#ff9800}\n')
    f.write('.rm{display:grid;grid-template-columns:repeat(2,1fr);gap:16px;margin-bottom:24px}\n')
    f.write('.ri{padding:16px;border-radius:8px;border-left:4px solid}\n')
    f.write('.ri.lw{background:#e6f4ea;border-left-color:var(--gg)}\n')
    f.write('.ri.md{background:#fff8e6;border-left-color:var(--gy)}\n')
    f.write('.ri.hg{background:#fce8e8;border-left-color:var(--gr)}\n')
    f.write('.ri .rt{font-size:13px;font-weight:700;text-transform:uppercase;letter-spacing:1px;margin-bottom:4px}\n')
    f.write('.ri .rd{font-size:13px;color:#5f6368}\n')
    f.write('.bc{margin:16px 0}\n')
    f.write('.br{display:flex;align-items:center;margin-bottom:12px}\n')
    f.write('.bl{width:140px;font-size:13px;font-weight:600;color:#3c4043;text-align:right;padding-right:12px}\n')
    f.write('.btk{flex:1;height:28px;background:#f1f3f4;border-radius:4px;overflow:hidden;position:relative}\n')
    f.write('.bf{height:100%;border-radius:4px;display:flex;align-items:center;justify-content:flex-end;padding-right:8px;font-size:12px;font-weight:600;font-family:"Roboto Mono",monospace;color:white}\n')
    f.write('.bf.b{background:var(--gb)}\n')
    f.write('.bf.g{background:var(--gg)}\n')
    f.write('.bf.r{background:var(--gr)}\n')
    f.write('.bf.gd{background:var(--gsg);color:var(--gsn)}\n')
    f.write('.bv{width:60px;font-size:13px;font-weight:600;font-family:"Roboto Mono",monospace;padding-left:8px;color:#3c4043}\n')
    f.write('.pf{margin-top:48px;padding-top:24px;border-top:1px solid #e8eaed;font-size:11px;color:#9aa0a6;display:flex;justify-content:space-between}\n')
    f.write('.dc{background:#f8f9fa;border-radius:8px;padding:16px;font-size:11px;color:#5f6368;line-height:1.6;margin-top:24px;border-left:3px solid var(--gy)}\n')
    f.write('.tc{display:grid;grid-template-columns:1fr 1fr;gap:24px}\n')
    f.write('.bn{font-size:48px;font-weight:800;font-family:"Roboto Mono",monospace;color:var(--gsn);line-height:1}\n')
    f.write('.bnl{font-size:12px;text-transform:uppercase;letter-spacing:2px;color:var(--ggr);margin-top:8px;font-weight:600}\n')
    f.write('@media print{.page{padding:32px 48px}.cover{height:100vh;page-break-after:always}}\n')
    f.write('</style></head><body>\n')

    # 封面
    f.write('<div class="cover">\n')
    f.write('  <div style="position:absolute;top:40px;right:40px;background:rgba(201,162,39,0.15);border:1px solid var(--gsg);color:var(--gsg);padding:8px 20px;border-radius:4px;font-size:12px;font-weight:600;letter-spacing:2px;text-transform:uppercase">机密 | 客户专供</div>\n')
    f.write('  <h1>伊朗 vs 新西兰</h1>\n')
    f.write('  <div class="cs">2026 FIFA世界杯 - 小组赛情报分析</div>\n')
    f.write('  <div class="cm">\n')
    f.write('    <div class="cmi"><div class="l">比赛日期</div><div class="v">2026-06-15</div></div>\n')
    f.write('    <div class="cmi"><div class="l">比赛场地</div><div class="v">待定</div></div>\n')
    f.write('    <div class="cmi"><div class="l">模型版本</div><div class="v">FQOS v5.2.0</div></div>\n')
    f.write('    <div class="cmi"><div class="l">爆冷指数</div><div class="v">24/100</div></div>\n')
    f.write('  </div>\n')
    f.write('  <div class="cf">FOOTBALL QUANT OS - NAGA CORE v5.0 - 2026-06-16 00:03 CST</div>\n')
    f.write('</div>\n')

    # 执行摘要
    f.write('<div class="page">\n')
    f.write('  <div class="sh"><div class="sn">1</div><div class="st">执行摘要</div></div>\n')
    f.write('  <div class="es">\n')
    f.write('    <h3>核心结论</h3>\n')
    f.write('    <div class="mc">模型预测新西兰胜率36.6%，而市场隐含概率仅12.6%——优势+24%，这是本次世界杯小组赛最大的市场错误定价之一！伊朗虽然FIFA排名更高，但市场赔率1.56隐含63.5%胜率，模型仅预测39.1%——高估24.4%。</div>\n')
    f.write('    <ul class="sp">\n')
    f.write('      <li><strong>市场优势：</strong>新西兰胜@5.40（+24%优势）和伊朗让1球盘口（+15%优势）是最高价值仓位</li>\n')
    f.write('      <li><strong>500.com投注情报：</strong>主流盘口伊朗让1球，受让方新西兰赔率2.07-2.25。市场过度追捧伊朗</li>\n')
    f.write('      <li><strong>模型置信度：</strong>8模型集成，爆冷指数24。泊松λ=2.65，总进球预期2-3球</li>\n')
    f.write('      <li><strong>历史参考：</strong>新西兰2026年首次参赛，伊朗亚洲劲旅但大赛表现不稳定</li>\n')
    f.write('    </ul>\n')
    f.write('  </div>\n')
    f.write('  <div class="mg">\n')
    f.write('    <div class="mcd"><div class="mv up">36.6%</div><div class="ml">新西兰模型胜率</div><div class="ms">市场隐含仅12.6%</div></div>\n')
    f.write('    <div class="mcd"><div class="mv up">+24.0%</div><div class="ml">新西兰胜 Edge</div><div class="ms">市场错误定价</div></div>\n')
    f.write('    <div class="mcd"><div class="mv">2.65</div><div class="ml">泊松λ</div><div class="ms">总进球预期</div></div>\n')
    f.write('  </div>\n')
    f.write('  <div class="card">\n')
    f.write('    <div class="ch"><div class="ct">关键统计</div><div class="cbd bdb">数据驱动</div></div>\n')
    f.write('    <div class="tc">\n')
    f.write('      <div><div class="bn">964</div><div class="bnl">历史比赛数据 (1930-2022)</div></div>\n')
    f.write('      <div><div class="bn">34</div><div class="bnl">模型特征 (CRI + FIFA + xG)</div></div>\n')
    f.write('    </div>\n')
    f.write('  </div>\n')
    f.write('</div>\n')

print('Part 1 IN written')
