#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
WORLD_CUP_2026_FULL_COACHES - 2026 World Cup 48 Teams Full Coach Database
Based on actual head coach data (June 2026 latest)

Data Sources: bolavip.com, soccerphile.com, transfermarkt.com, thedailycircular.ng, vanguardngr.com
Data update date: 2026-06-13
"""

from agents.coach_types import CoachProfile, TacticalStyle

# ============================================================
# 2026 World Cup 48 Teams Head Coach Full Database
# ============================================================

WORLD_CUP_2026_FULL_COACHES = {
    # CONCACAF (6 teams)
    'USA': CoachProfile(name='Mauricio Pochettino', nationality='Argentina', age=54, tactical_style=TacticalStyle.PRESS, formation_flexibility=3.5, avg_formations_per_tournament=2.5, world_cup_experience=0, euro_experience=0, knockout_stage_wins=0, emotional_stability=7.0, media_influence_susceptibility=4.0, team_meltdown_incidents=0, rotation_tendency=4.0, vs_strong_team_strategy='balanced', vs_weak_team_strategy='aggressive', strategy_extremity=3.0, avg_goals_per_match=1.9, avg_conceded_per_match=1.2),
    'Mexico': CoachProfile(name='Javier Aguirre', nationality='Mexico', age=66, tactical_style=TacticalStyle.COUNTER, formation_flexibility=3.0, avg_formations_per_tournament=2.0, world_cup_experience=2, euro_experience=0, knockout_stage_wins=2, emotional_stability=6.0, media_influence_susceptibility=5.0, team_meltdown_incidents=1, rotation_tendency=4.0, vs_strong_team_strategy='defensive', vs_weak_team_strategy='aggressive', strategy_extremity=3.5, avg_goals_per_match=1.5, avg_conceded_per_match=1.2),
    'Canada': CoachProfile(name='Jesse Marsch', nationality='USA', age=50, tactical_style=TacticalStyle.PRESS, formation_flexibility=5.0, avg_formations_per_tournament=3.0, world_cup_experience=0, euro_experience=0, knockout_stage_wins=0, emotional_stability=5.0, media_influence_susceptibility=6.0, team_meltdown_incidents=2, rotation_tendency=6.0, vs_strong_team_strategy='aggressive', vs_weak_team_strategy='aggressive', strategy_extremity=5.0, avg_goals_per_match=1.8, avg_conceded_per_match=1.0),
    'Panama': CoachProfile(name='Thomas Christiansen', nationality='Spain', age=53, tactical_style=TacticalStyle.COUNTER, formation_flexibility=2.5, avg_formations_per_tournament=1.8, world_cup_experience=0, euro_experience=0, knockout_stage_wins=0, emotional_stability=6.5, media_influence_susceptibility=4.0, team_meltdown_incidents=0, rotation_tendency=3.5, vs_strong_team_strategy='defensive', vs_weak_team_strategy='balanced', strategy_extremity=2.5, avg_goals_per_match=1.2, avg_conceded_per_match=1.3),
    'Haiti': CoachProfile(name='Sebastien Migne', nationality='France', age=52, tactical_style=TacticalStyle.COUNTER, formation_flexibility=3.0, avg_formations_per_tournament=2.0, world_cup_experience=0, euro_experience=0, knockout_stage_wins=0, emotional_stability=5.5, media_influence_susceptibility=5.0, team_meltdown_incidents=1, rotation_tendency=4.0, vs_strong_team_strategy='defensive', vs_weak_team_strategy='balanced', strategy_extremity=3.0, avg_goals_per_match=1.0, avg_conceded_per_match=1.5),
    'Curacao': CoachProfile(name='Dick Advocaat', nationality='Netherlands', age=77, tactical_style=TacticalStyle.CONTROL, formation_flexibility=2.0, avg_formations_per_tournament=1.5, world_cup_experience=3, euro_experience=0, knockout_stage_wins=2, emotional_stability=7.0, media_influence_susceptibility=3.0, team_meltdown_incidents=0, rotation_tendency=3.0, vs_strong_team_strategy='defensive', vs_weak_team_strategy='balanced', strategy_extremity=2.0, avg_goals_per_match=1.0, avg_conceded_per_match=1.2),
    
    # CONMEBOL (6 teams)
    'Argentina': CoachProfile(name='Lionel Scaloni', nationality='Argentina', age=46, tactical_style=TacticalStyle.PRESS, formation_flexibility=3.0, avg_formations_per_tournament=2.0, world_cup_experience=1, euro_experience=0, knockout_stage_wins=6, emotional_stability=8.0, media_influence_susceptibility=3.0, team_meltdown_incidents=0, rotation_tendency=4.0, vs_strong_team_strategy='balanced', vs_weak_team_strategy='aggressive', strategy_extremity=3.0, avg_goals_per_match=2.2, avg_conceded_per_match=0.8),
    'Brazil': CoachProfile(name='Carlo Ancelotti', nationality='Italy', age=66, tactical_style=TacticalStyle.CONTROL, formation_flexibility=2.5, avg_formations_per_tournament=2.0, world_cup_experience=0, euro_experience=0, knockout_stage_wins=0, emotional_stability=9.0, media_influence_susceptibility=2.0, team_meltdown_incidents=0, rotation_tendency=3.5, vs_strong_team_strategy='balanced', vs_weak_team_strategy='aggressive', strategy_extremity=2.0, avg_goals_per_match=2.0, avg_conceded_per_match=0.9),
    'Colombia': CoachProfile(name='Nestor Lorenzo', nationality='Argentina', age=60, tactical_style=TacticalStyle.PRESS, formation_flexibility=3.0, avg_formations_per_tournament=2.0, world_cup_experience=0, euro_experience=0, knockout_stage_wins=0, emotional_stability=6.5, media_influence_susceptibility=4.0, team_meltdown_incidents=0, rotation_tendency=3.5, vs_strong_team_strategy='balanced', vs_weak_team_strategy='aggressive', strategy_extremity=3.0, avg_goals_per_match=1.6, avg_conceded_per_match=1.0),
    'Ecuador': CoachProfile(name='Sebastian Beccacece', nationality='Argentina', age=44, tactical_style=TacticalStyle.PRESS, formation_flexibility=4.0, avg_formations_per_tournament=2.5, world_cup_experience=0, euro_experience=0, knockout_stage_wins=0, emotional_stability=5.5, media_influence_susceptibility=5.0, team_meltdown_incidents=1, rotation_tendency=4.5, vs_strong_team_strategy='aggressive', vs_weak_team_strategy='aggressive', strategy_extremity=4.0, avg_goals_per_match=1.5, avg_conceded_per_match=1.2),
    'Paraguay': CoachProfile(name='Gustavo Alfaro', nationality='Argentina', age=58, tactical_style=TacticalStyle.COUNTER, formation_flexibility=3.0, avg_formations_per_tournament=2.0, world_cup_experience=0, euro_experience=0, knockout_stage_wins=0, emotional_stability=7.0, media_influence_susceptibility=4.0, team_meltdown_incidents=0, rotation_tendency=4.0, vs_strong_team_strategy='defensive', vs_weak_team_strategy='balanced', strategy_extremity=3.0, avg_goals_per_match=1.2, avg_conceded_per_match=1.0),
    'Uruguay': CoachProfile(name='Marcelo Bielsa', nationality='Argentina', age=70, tactical_style=TacticalStyle.EXTREME, formation_flexibility=4.5, avg_formations_per_tournament=3.0, world_cup_experience=2, euro_experience=0, knockout_stage_wins=2, emotional_stability=5.0, media_influence_susceptibility=6.0, team_meltdown_incidents=1, rotation_tendency=5.0, vs_strong_team_strategy='aggressive', vs_weak_team_strategy='aggressive', strategy_extremity=5.0, avg_goals_per_match=1.8, avg_conceded_per_match=1.1),
    
    # AFC (9 teams)
    'Japan': CoachProfile(name='Hajime Moriyasu', nationality='Japan', age=57, tactical_style=TacticalStyle.PRESS, formation_flexibility=2.5, avg_formations_per_tournament=2.0, world_cup_experience=1, euro_experience=0, knockout_stage_wins=1, emotional_stability=7.5, media_influence_susceptibility=3.0, team_meltdown_incidents=0, rotation_tendency=3.5, vs_strong_team_strategy='balanced', vs_weak_team_strategy='aggressive', strategy_extremity=2.5, avg_goals_per_match=1.8, avg_conceded_per_match=0.9),
    'Iran': CoachProfile(name='Amir Ghalenoei', nationality='Iran', age=62, tactical_style=TacticalStyle.COUNTER, formation_flexibility=2.5, avg_formations_per_tournament=1.8, world_cup_experience=0, euro_experience=0, knockout_stage_wins=0, emotional_stability=6.0, media_influence_susceptibility=5.0, team_meltdown_incidents=1, rotation_tendency=3.0, vs_strong_team_strategy='defensive', vs_weak_team_strategy='balanced', strategy_extremity=2.5, avg_goals_per_match=1.3, avg_conceded_per_match=1.0),
    'Korea_Republic': CoachProfile(name='Hong Myung-bo', nationality='Korea Republic', age=55, tactical_style=TacticalStyle.PRESS, formation_flexibility=3.0, avg_formations_per_tournament=2.0, world_cup_experience=1, euro_experience=0, knockout_stage_wins=0, emotional_stability=6.0, media_influence_susceptibility=5.0, team_meltdown_incidents=1, rotation_tendency=3.5, vs_strong_team_strategy='balanced', vs_weak_team_strategy='aggressive', strategy_extremity=3.0, avg_goals_per_match=1.5, avg_conceded_per_match=1.1),
    'Australia': CoachProfile(name='Tony Popovic', nationality='Australia', age=51, tactical_style=TacticalStyle.PRESS, formation_flexibility=3.0, avg_formations_per_tournament=2.0, world_cup_experience=0, euro_experience=0, knockout_stage_wins=0, emotional_stability=6.5, media_influence_susceptibility=4.0, team_meltdown_incidents=0, rotation_tendency=3.5, vs_strong_team_strategy='balanced', vs_weak_team_strategy='aggressive', strategy_extremity=3.0, avg_goals_per_match=1.4, avg_conceded_per_match=1.2),
    'Uzbekistan': CoachProfile(name='Fabio Cannavaro', nationality='Italy', age=52, tactical_style=TacticalStyle.CONTROL, formation_flexibility=2.5, avg_formations_per_tournament=2.0, world_cup_experience=0, euro_experience=0, knockout_stage_wins=0, emotional_stability=6.5, media_influence_susceptibility=4.0, team_meltdown_incidents=0, rotation_tendency=3.0, vs_strong_team_strategy='balanced', vs_weak_team_strategy='aggressive', strategy_extremity=2.5, avg_goals_per_match=1.3, avg_conceded_per_match=1.0),
    'Jordan': CoachProfile(name='Jamal Sellami', nationality='Morocco', age=54, tactical_style=TacticalStyle.COUNTER, formation_flexibility=3.0, avg_formations_per_tournament=2.0, world_cup_experience=0, euro_experience=0, knockout_stage_wins=0, emotional_stability=5.5, media_influence_susceptibility=5.0, team_meltdown_incidents=1, rotation_tendency=4.0, vs_strong_team_strategy='defensive', vs_weak_team_strategy='balanced', strategy_extremity=3.0, avg_goals_per_match=1.1, avg_conceded_per_match=1.2),
    'Qatar': CoachProfile(name='Julen Lopetegui', nationality='Spain', age=58, tactical_style=TacticalStyle.CONTROL, formation_flexibility=2.5, avg_formations_per_tournament=2.0, world_cup_experience=1, euro_experience=1, knockout_stage_wins=0, emotional_stability=5.0, media_influence_susceptibility=5.0, team_meltdown_incidents=1, rotation_tendency=3.5, vs_strong_team_strategy='balanced', vs_weak_team_strategy='aggressive', strategy_extremity=2.5, avg_goals_per_match=1.5, avg_conceded_per_match=1.1),
    'Saudi_Arabia': CoachProfile(name='Georgios Donis', nationality='Greece', age=55, tactical_style=TacticalStyle.COUNTER, formation_flexibility=3.0, avg_formations_per_tournament=2.0, world_cup_experience=0, euro_experience=0, knockout_stage_wins=0, emotional_stability=6.0, media_influence_susceptibility=4.0, team_meltdown_incidents=0, rotation_tendency=3.5, vs_strong_team_strategy='defensive', vs_weak_team_strategy='balanced', strategy_extremity=3.0, avg_goals_per_match=1.2, avg_conceded_per_match=1.1),
    'Iraq': CoachProfile(name='Graham Arnold', nationality='Australia', age=61, tactical_style=TacticalStyle.CONTROL, formation_flexibility=3.0, avg_formations_per_tournament=2.0, world_cup_experience=1, euro_experience=0, knockout_stage_wins=0, emotional_stability=6.0, media_influence_susceptibility=4.0, team_meltdown_incidents=0, rotation_tendency=3.5, vs_strong_team_strategy='balanced', vs_weak_team_strategy='aggressive', strategy_extremity=2.5, avg_goals_per_match=1.3, avg_conceded_per_match=1.1),
    
    # CAF (10 teams)
    'Morocco': CoachProfile(name='Mohamed Ouahbi', nationality='Morocco', age=49, tactical_style=TacticalStyle.COUNTER, formation_flexibility=2.5, avg_formations_per_tournament=2.0, world_cup_experience=0, euro_experience=0, knockout_stage_wins=0, emotional_stability=6.0, media_influence_susceptibility=4.0, team_meltdown_incidents=0, rotation_tendency=3.5, vs_strong_team_strategy='defensive', vs_weak_team_strategy='balanced', strategy_extremity=2.5, avg_goals_per_match=1.4, avg_conceded_per_match=0.8),
    'Senegal': CoachProfile(name='Pape Thiaw', nationality='Senegal', age=45, tactical_style=TacticalStyle.PRESS, formation_flexibility=3.5, avg_formations_per_tournament=2.5, world_cup_experience=0, euro_experience=0, knockout_stage_wins=0, emotional_stability=5.5, media_influence_susceptibility=5.0, team_meltdown_incidents=1, rotation_tendency=4.5, vs_strong_team_strategy='balanced', vs_weak_team_strategy='aggressive', strategy_extremity=3.5, avg_goals_per_match=1.5, avg_conceded_per_match=1.1),
    'Egypt': CoachProfile(name='Hossam Hassan', nationality='Egypt', age=58, tactical_style=TacticalStyle.CONTROL, formation_flexibility=2.5, avg_formations_per_tournament=1.8, world_cup_experience=3, euro_experience=0, knockout_stage_wins=0, emotional_stability=5.0, media_influence_susceptibility=6.0, team_meltdown_incidents=2, rotation_tendency=3.0, vs_strong_team_strategy='defensive', vs_weak_team_strategy='balanced', strategy_extremity=2.5, avg_goals_per_match=1.2, avg_conceded_per_match=1.0),
    'Tunisia': CoachProfile(name='Sabri Lamouchi', nationality='France', age=53, tactical_style=TacticalStyle.COUNTER, formation_flexibility=3.0, avg_formations_per_tournament=2.0, world_cup_experience=1, euro_experience=0, knockout_stage_wins=0, emotional_stability=6.0, media_influence_susceptibility=4.0, team_meltdown_incidents=0, rotation_tendency=3.5, vs_strong_team_strategy='defensive', vs_weak_team_strategy='balanced', strategy_extremity=2.5, avg_goals_per_match=1.1, avg_conceded_per_match=1.2),
    'Algeria': CoachProfile(name='Vladimir Petkovic', nationality='Bosnia', age=61, tactical_style=TacticalStyle.CONTROL, formation_flexibility=2.5, avg_formations_per_tournament=2.0, world_cup_experience=1, euro_experience=1, knockout_stage_wins=1, emotional_stability=7.0, media_influence_susceptibility=3.0, team_meltdown_incidents=0, rotation_tendency=3.0, vs_strong_team_strategy='balanced', vs_weak_team_strategy='aggressive', strategy_extremity=2.0, avg_goals_per_match=1.5, avg_conceded_per_match=0.9),
    'South_Africa': CoachProfile(name='Hugo Broos', nationality='Belgium', age=74, tactical_style=TacticalStyle.CONTROL, formation_flexibility=2.0, avg_formations_per_tournament=1.5, world_cup_experience=1, euro_experience=0, knockout_stage_wins=1, emotional_stability=7.0, media_influence_susceptibility=3.0, team_meltdown_incidents=0, rotation_tendency=3.0, vs_strong_team_strategy='defensive', vs_weak_team_strategy='balanced', strategy_extremity=2.0, avg_goals_per_match=1.0, avg_conceded_per_match=1.0),
    'Cote_dIvoire': CoachProfile(name='Emerse Fae', nationality='Ivory Coast', age=40, tactical_style=TacticalStyle.PRESS, formation_flexibility=4.0, avg_formations_per_tournament=2.5, world_cup_experience=0, euro_experience=0, knockout_stage_wins=2, emotional_stability=5.5, media_influence_susceptibility=5.0, team_meltdown_incidents=1, rotation_tendency=4.5, vs_strong_team_strategy='aggressive', vs_weak_team_strategy='aggressive', strategy_extremity=4.0, avg_goals_per_match=1.6, avg_conceded_per_match=1.2),
    'Ghana': CoachProfile(name='Carlos Queiroz', nationality='Portugal', age=72, tactical_style=TacticalStyle.CONTROL, formation_flexibility=2.0, avg_formations_per_tournament=1.5, world_cup_experience=3, euro_experience=0, knockout_stage_wins=1, emotional_stability=7.5, media_influence_susceptibility=3.0, team_meltdown_incidents=0, rotation_tendency=3.0, vs_strong_team_strategy='balanced', vs_weak_team_strategy='aggressive', strategy_extremity=2.0, avg_goals_per_match=1.3, avg_conceded_per_match=1.1),
    'Cape_Verde': CoachProfile(name='Bubista', nationality='Cape Verde', age=56, tactical_style=TacticalStyle.COUNTER, formation_flexibility=2.5, avg_formations_per_tournament=1.8, world_cup_experience=0, euro_experience=0, knockout_stage_wins=0, emotional_stability=6.0, media_influence_susceptibility=4.0, team_meltdown_incidents=0, rotation_tendency=3.0, vs_strong_team_strategy='defensive', vs_weak_team_strategy='balanced', strategy_extremity=2.5, avg_goals_per_match=1.0, avg_conceded_per_match=1.1),
    'DR_Congo': CoachProfile(name='Sebastien Desabre', nationality='France', age=49, tactical_style=TacticalStyle.CONTROL, formation_flexibility=3.0, avg_formations_per_tournament=2.0, world_cup_experience=0, euro_experience=0, knockout_stage_wins=0, emotional_stability=6.0, media_influence_susceptibility=4.0, team_meltdown_incidents=0, rotation_tendency=3.5, vs_strong_team_strategy='balanced', vs_weak_team_strategy='aggressive', strategy_extremity=2.5, avg_goals_per_match=1.2, avg_conceded_per_match=1.1),
    
    # UEFA (16 teams)
    'France': CoachProfile(name='Didier Deschamps', nationality='France', age=57, tactical_style=TacticalStyle.CONTROL, formation_flexibility=2.0, avg_formations_per_tournament=1.5, world_cup_experience=3, euro_experience=2, knockout_stage_wins=8, emotional_stability=9.0, media_influence_susceptibility=2.0, team_meltdown_incidents=0, rotation_tendency=3.5, vs_strong_team_strategy='balanced', vs_weak_team_strategy='aggressive', strategy_extremity=2.0, avg_goals_per_match=2.1, avg_conceded_per_match=0.9),
    'Spain': CoachProfile(name='Luis de la Fuente', nationality='Spain', age=64, tactical_style=TacticalStyle.CONTROL, formation_flexibility=2.5, avg_formations_per_tournament=2.0, world_cup_experience=0, euro_experience=1, knockout_stage_wins=4, emotional_stability=7.5, media_influence_susceptibility=3.0, team_meltdown_incidents=0, rotation_tendency=3.0, vs_strong_team_strategy='balanced', vs_weak_team_strategy='aggressive', strategy_extremity=2.5, avg_goals_per_match=2.0, avg_conceded_per_match=0.8),
    'England': CoachProfile(name='Thomas Tuchel', nationality='Germany', age=51, tactical_style=TacticalStyle.PRESS, formation_flexibility=3.5, avg_formations_per_tournament=2.5, world_cup_experience=0, euro_experience=0, knockout_stage_wins=0, emotional_stability=6.0, media_influence_susceptibility=5.0, team_meltdown_incidents=1, rotation_tendency=4.0, vs_strong_team_strategy='aggressive', vs_weak_team_strategy='aggressive', strategy_extremity=3.5, avg_goals_per_match=1.9, avg_conceded_per_match=1.0),
    'Portugal': CoachProfile(name='Roberto Martinez', nationality='Spain', age=52, tactical_style=TacticalStyle.CONTROL, formation_flexibility=2.5, avg_formations_per_tournament=2.0, world_cup_experience=1, euro_experience=0, knockout_stage_wins=1, emotional_stability=7.0, media_influence_susceptibility=3.0, team_meltdown_incidents=0, rotation_tendency=3.5, vs_strong_team_strategy='balanced', vs_weak_team_strategy='aggressive', strategy_extremity=2.5, avg_goals_per_match=2.0, avg_conceded_per_match=0.9),
    'Germany': CoachProfile(name='Julian Nagelsmann', nationality='Germany', age=38, tactical_style=TacticalStyle.PRESS, formation_flexibility=4.0, avg_formations_per_tournament=2.5, world_cup_experience=0, euro_experience=1, knockout_stage_wins=1, emotional_stability=6.0, media_influence_susceptibility=4.0, team_meltdown_incidents=1, rotation_tendency=4.5, vs_strong_team_strategy='aggressive', vs_weak_team_strategy='aggressive', strategy_extremity=4.0, avg_goals_per_match=2.0, avg_conceded_per_match=1.1),
    'Netherlands': CoachProfile(name='Ronald Koeman', nationality='Netherlands', age=61, tactical_style=TacticalStyle.CONTROL, formation_flexibility=2.5, avg_formations_per_tournament=2.0, world_cup_experience=0, euro_experience=1, knockout_stage_wins=1, emotional_stability=5.5, media_influence_susceptibility=5.0, team_meltdown_incidents=1, rotation_tendency=3.5, vs_strong_team_strategy='balanced', vs_weak_team_strategy='aggressive', strategy_extremity=3.0, avg_goals_per_match=1.8, avg_conceded_per_match=1.0),
    'Belgium': CoachProfile(name='Rudi Garcia', nationality='France', age=61, tactical_style=TacticalStyle.CONTROL, formation_flexibility=3.0, avg_formations_per_tournament=2.0, world_cup_experience=0, euro_experience=0, knockout_stage_wins=0, emotional_stability=6.0, media_influence_susceptibility=4.0, team_meltdown_incidents=1, rotation_tendency=3.5, vs_strong_team_strategy='balanced', vs_weak_team_strategy='aggressive', strategy_extremity=3.0, avg_goals_per_match=1.7, avg_conceded_per_match=1.0),
    'Croatia': CoachProfile(name='Zlatko Dalic', nationality='Croatia', age=59, tactical_style=TacticalStyle.CONTROL, formation_flexibility=2.5, avg_formations_per_tournament=2.0, world_cup_experience=2, euro_experience=1, knockout_stage_wins=5, emotional_stability=7.5, media_influence_susceptibility=3.0, team_meltdown_incidents=0, rotation_tendency=3.0, vs_strong_team_strategy='balanced', vs_weak_team_strategy='aggressive', strategy_extremity=2.5, avg_goals_per_match=1.8, avg_conceded_per_match=0.9),
    'Switzerland': CoachProfile(name='Murat Yakin', nationality='Switzerland', age=51, tactical_style=TacticalStyle.CONTROL, formation_flexibility=2.5, avg_formations_per_tournament=2.0, world_cup_experience=2, euro_experience=1, knockout_stage_wins=2, emotional_stability=7.0, media_influence_susceptibility=3.0, team_meltdown_incidents=0, rotation_tendency=3.0, vs_strong_team_strategy='balanced', vs_weak_team_strategy='aggressive', strategy_extremity=2.5, avg_goals_per_match=1.6, avg_conceded_per_match=0.9),
    'Austria': CoachProfile(name='Ralf Rangnick', nationality='Germany', age=67, tactical_style=TacticalStyle.PRESS, formation_flexibility=4.0, avg_formations_per_tournament=2.5, world_cup_experience=0, euro_experience=1, knockout_stage_wins=0, emotional_stability=6.5, media_influence_susceptibility=4.0, team_meltdown_incidents=1, rotation_tendency=4.0, vs_strong_team_strategy='aggressive', vs_weak_team_strategy='aggressive', strategy_extremity=3.5, avg_goals_per_match=1.7, avg_conceded_per_match=1.0),
    'Scotland': CoachProfile(name='Steve Clarke', nationality='Scotland', age=62, tactical_style=TacticalStyle.COUNTER, formation_flexibility=2.5, avg_formations_per_tournament=1.8, world_cup_experience=0, euro_experience=2, knockout_stage_wins=0, emotional_stability=6.5, media_influence_susceptibility=4.0, team_meltdown_incidents=0, rotation_tendency=3.0, vs_strong_team_strategy='defensive', vs_weak_team_strategy='balanced', strategy_extremity=2.5, avg_goals_per_match=1.3, avg_conceded_per_match=1.1),
    'Norway': CoachProfile(name='Stale Solbakken', nationality='Norway', age=58, tactical_style=TacticalStyle.CONTROL, formation_flexibility=2.5, avg_formations_per_tournament=2.0, world_cup_experience=0, euro_experience=0, knockout_stage_wins=0, emotional_stability=6.0, media_influence_susceptibility=4.0, team_meltdown_incidents=1, rotation_tendency=3.5, vs_strong_team_strategy='balanced', vs_weak_team_strategy='aggressive', strategy_extremity=2.5, avg_goals_per_match=1.6, avg_conceded_per_match=1.0),
    'Sweden': CoachProfile(name='Graham Potter', nationality='England', age=51, tactical_style=TacticalStyle.CONTROL, formation_flexibility=3.0, avg_formations_per_tournament=2.0, world_cup_experience=0, euro_experience=0, knockout_stage_wins=0, emotional_stability=6.5, media_influence_susceptibility=4.0, team_meltdown_incidents=0, rotation_tendency=3.5, vs_strong_team_strategy='balanced', vs_weak_team_strategy='aggressive', strategy_extremity=2.5, avg_goals_per_match=1.5, avg_conceded_per_match=1.0),
    'Türkiye': CoachProfile(name='Vincenzo Montella', nationality='Italy', age=51, tactical_style=TacticalStyle.PRESS, formation_flexibility=3.5, avg_formations_per_tournament=2.5, world_cup_experience=0, euro_experience=1, knockout_stage_wins=1, emotional_stability=6.0, media_influence_susceptibility=4.0, team_meltdown_incidents=1, rotation_tendency=4.0, vs_strong_team_strategy='aggressive', vs_weak_team_strategy='aggressive', strategy_extremity=3.5, avg_goals_per_match=1.8, avg_conceded_per_match=1.1),
    'Czechia': CoachProfile(name='Miroslav Koubek', nationality='Czechia', age=57, tactical_style=TacticalStyle.CONTROL, formation_flexibility=2.5, avg_formations_per_tournament=2.0, world_cup_experience=0, euro_experience=0, knockout_stage_wins=0, emotional_stability=6.0, media_influence_susceptibility=4.0, team_meltdown_incidents=0, rotation_tendency=3.0, vs_strong_team_strategy='balanced', vs_weak_team_strategy='aggressive', strategy_extremity=2.5, avg_goals_per_match=1.4, avg_conceded_per_match=1.0),
    'Bosnia_and_Herzegovina': CoachProfile(name='Sergej Barbarez', nationality='Bosnia', age=52, tactical_style=TacticalStyle.COUNTER, formation_flexibility=2.0, avg_formations_per_tournament=1.5, world_cup_experience=0, euro_experience=0, knockout_stage_wins=0, emotional_stability=6.0, media_influence_susceptibility=4.0, team_meltdown_incidents=0, rotation_tendency=3.0, vs_strong_team_strategy='defensive', vs_weak_team_strategy='balanced', strategy_extremity=2.0, avg_goals_per_match=1.0, avg_conceded_per_match=1.2),
    
    # OFC (1 team)
    'New_Zealand': CoachProfile(name='Darren Bazeley', nationality='UK', age=53, tactical_style=TacticalStyle.COUNTER, formation_flexibility=2.5, avg_formations_per_tournament=1.8, world_cup_experience=0, euro_experience=0, knockout_stage_wins=0, emotional_stability=6.0, media_influence_susceptibility=4.0, team_meltdown_incidents=0, rotation_tendency=3.0, vs_strong_team_strategy='defensive', vs_weak_team_strategy='balanced', strategy_extremity=2.5, avg_goals_per_match=1.0, avg_conceded_per_match=1.2),
}

# Total: 48 teams
# CONCACAF: 6, CONMEBOL: 6, AFC: 9, CAF: 10, UEFA: 16, OFC: 1
# Total = 48
